### ISSUE TITLE
no-commit-to-branch main pre-commit hook?

### ISSUE THREAD

**Issue by sbillinge** [NSLS-II/scientific-python-cookiecutter#120]
I would love to have this included in the pre-commit hooks, or included as an option.

pre-commit would become in the yaml
```
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: no-commit-to-branch
      args: ['--branch', 'main']
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
```
