### ISSUE TITLE
Is it save to keep a long key like string in .travis.yml ?

### ISSUE THREAD

**Issue by vstadnytskyi** [NSLS-II/scientific-python-cookiecutter#72]
So I have noticed there is a long string saved in .travis.yml. I wonder if that is some kind of key. Is it safe to have it there?
```
env:
    global:
      # Doctr deploy key for vstadnytskyi/my_package
      - secure: "xJPgTjsUjDmFIKdbk1iM4m/taLo1kxbr+eF1SMeHVn9azWDV/dX6Jjj/tkvp9ZO6+XVyhOF6dL9O0z3WaY
```
